Fix: Resolve TypeScript build error
The error `tsconfig.json(25,18): error TS6310: Referenced project '/dev-server/tsconfig.node.json' may not disable emit.` is caused by `noEmit: true` in `tsconfig.node.json`. This commit attempts to resolve the error.